-- 日記功能：每天可以有多筆日記紀錄，標籤依「分類」分組管理。
-- 分類/標籤是每個使用者自己的（不共用），存在 tag_categories.tags（文字陣列），
-- 不另外開一張 tags 表，跟隨資料量小、不值得多一層正規化的原則。

create table if not exists calendar.tag_categories (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  tags text[] not null default '{}',
  created_at timestamptz not null default now()
);

create index if not exists tag_categories_user_idx on calendar.tag_categories (user_id, created_at);

create table if not exists calendar.diary_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  entry_date date not null,
  all_day boolean not null default false,
  time text,
  end_time text,
  location text,
  people text[] not null default '{}',
  tags text[] not null default '{}',
  note text,
  created_at timestamptz not null default now()
);

create index if not exists diary_entries_user_date_idx on calendar.diary_entries (user_id, entry_date);

alter table calendar.tag_categories enable row level security;
alter table calendar.diary_entries enable row level security;

drop policy if exists "Users manage own tag categories" on calendar.tag_categories;
create policy "Users manage own tag categories"
  on calendar.tag_categories for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users manage own diary entries" on calendar.diary_entries;
create policy "Users manage own diary entries"
  on calendar.diary_entries for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

grant select, insert, update, delete on calendar.tag_categories to authenticated, service_role;
grant select, insert, update, delete on calendar.diary_entries to authenticated, service_role;
