-- 週期性任務：每 N 天/週/月做一次的家務事之類，標記完成後自動算出下次到期日。
-- 完成歷史直接存日期陣列（跟 tag_categories.tags 一樣的簡化做法），不另開子表。

create table if not exists calendar.tasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  interval_value int not null default 1,
  interval_unit text not null default 'month' check (interval_unit in ('day', 'week', 'month')),
  next_due date not null,
  last_done date,
  show_on_calendar boolean not null default true,
  history date[] not null default '{}',
  created_at timestamptz not null default now()
);

create index if not exists tasks_user_due_idx on calendar.tasks (user_id, next_due);

alter table calendar.tasks enable row level security;

drop policy if exists "Users manage own tasks" on calendar.tasks;
create policy "Users manage own tasks"
  on calendar.tasks for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

grant select, insert, update, delete on calendar.tasks to authenticated, service_role;
