-- 地點/人名/事件標籤的選項庫：表單下拉選單與設定頁「管理地點、人名與標籤」的資料來源。
-- 封存（archived=true）後選單不再出現，但過去事件/日記存的文字照舊保留。
-- 事件標籤（kind='tag'）可以有一層子標籤：parent_id 指向母標籤；地點/人名一律 parent_id null。

create table if not exists calendar.event_options (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null check (kind in ('location', 'person', 'tag')),
  name text not null,
  parent_id bigint references calendar.event_options(id) on delete cascade,
  archived boolean not null default false,
  created_at timestamptz not null default now()
);

-- 同層同名不重複（頂層 parent_id null 視為同一層）
create unique index if not exists event_options_unique_idx
  on calendar.event_options (user_id, kind, name, coalesce(parent_id, 0));

alter table calendar.event_options enable row level security;

drop policy if exists "Users manage own event options" on calendar.event_options;
create policy "Users manage own event options"
  on calendar.event_options for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

grant select, insert, update, delete on calendar.event_options to authenticated, service_role;

-- 回填：既有事件/日記曾用過的地點、人名（兩邊共用同一池）、事件標籤（成為頂層標籤）
insert into calendar.event_options (user_id, kind, name)
select distinct user_id, 'location', trim(location) from calendar.events
  where location is not null and trim(location) <> ''
union
select distinct user_id, 'location', trim(location) from calendar.diary_entries
  where location is not null and trim(location) <> ''
on conflict do nothing;

insert into calendar.event_options (user_id, kind, name)
select distinct user_id, 'person', trim(p) from calendar.events, unnest(people) as p
  where trim(p) <> ''
union
select distinct user_id, 'person', trim(p) from calendar.diary_entries, unnest(people) as p
  where trim(p) <> ''
on conflict do nothing;

insert into calendar.event_options (user_id, kind, name)
select distinct user_id, 'tag', trim(t) from calendar.events, unnest(tags) as t
  where trim(t) <> ''
on conflict do nothing;
