-- Calendar schema
-- 一次跑完即可建立 calendar schema + events 表 + RLS。

create schema if not exists calendar;
grant usage on schema calendar to anon, authenticated, service_role;

create table if not exists calendar.events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  description text,
  start_at timestamptz not null,
  end_at timestamptz,
  all_day boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists events_user_start_idx on calendar.events (user_id, start_at);

-- RLS：每個人只能看/改自己的事件，純個人行程管理，沒有分享機制
alter table calendar.events enable row level security;

drop policy if exists "Users manage own events" on calendar.events;
create policy "Users manage own events"
  on calendar.events for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

grant select, insert, update, delete on calendar.events to authenticated, service_role;
