-- Recipe Book schema
-- 一次跑完即可建立 recipes 表 + 公開讀取的 RLS policy。
-- cooking_history（料理行事曆紀錄）放在 2026-06-28_recipe_cook_records.sql migration，
-- 直接建在 recipe_book schema，所以這份 schema.sql 不再含 cooking_history。

create extension if not exists pgcrypto;

create table if not exists public.recipes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null, -- 擁有者
  is_shared boolean not null default false,                  -- 是否分享給其他人（含未登入訪客）看
  title text not null,
  category text[] default '{}',          -- 多分類標籤
  ingredients jsonb default '[]'::jsonb, -- [{ name, amount, unit, ... }]
  steps jsonb default '[]'::jsonb,       -- [{ order, text, ... }]
  notes text,
  image_url text,
  last_cooked_at timestamptz,
  yield_info jsonb default '[]'::jsonb,  -- 份量/產出資訊
  parameters jsonb default '{}'::jsonb,  -- 動態製作參數（溫度、時間、配方比例等）
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists recipes_category_gin on public.recipes using gin (category);
create index if not exists recipes_title_idx on public.recipes (title);
create index if not exists recipes_user_id_idx on public.recipes (user_id);
create index if not exists recipes_is_shared_idx on public.recipes (is_shared) where is_shared = true;

-- RLS 設定見 2026-06-28_recipe_ownership.sql（讀: is_shared or 擁有者；寫: 只有擁有者）
alter table public.recipes enable row level security;
